<a href="https://colab.research.google.com/github/SanjayD23/Alphabetical-Hand-gesture-recognition-using-deep-leaning/blob/main/Alphabetical_Hand_gesture_recognition_using_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install scikit-learn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [4]:
import os
data_path = "/content/drive/MyDrive"
os.chdir(data_path)
os.listdir(data_path)

['CV (2).pdf',
 'CV (1).pdf',
 'Classroom',
 'NCC reigistration(ige).gsheet',
 'Colab Notebooks',
 'e-certificate no (89).pdf',
 'BCA 5th sem.gsheet',
 'Sanjay Kumar Das Minor Project Food Delivery website[Grp.5].gslides',
 'Sanjay Kumar Das(Cyber Security 024).gslides',
 'Sanjay Kumar Das( E-Commerce 024).gslides',
 'Sanjay Kumar Das(Unix and shell Programming 024).gslides',
 'My Projects>>',
 'XHJ1114800.pdf',
 'Ethical Hacking',
 'Sanjay Kumar das.pdf',
 'FAQs on GRIP.gdoc',
 'Internship ',
 'Sanjay Kumar Das(Ethical hacking Course 2024).gslides',
 'Cv (1).pdf',
 'Cv.pdf',
 'CV.pdf',
 'Sanjay Kumar Das_photo (1).png',
 'Sanjay Kumar Das_photo.png',
 '1000019353-removebg-preview.png',
 'Sanjay Kumar Das_Declaration of Admission.pdf',
 'Sanjay Kumar Das_Fee Receipt.pdf',
 'Reg_PG (1).pdf',
 'Sanjay Kumar Das_Declaration.pdf',
 'Sanjay Kumar Das_Fee Receipt (1).pdf',
 '10th marksheet.pdf',
 '12th marksheet.pdf',
 'Scientific_Computing.gdoc',
 'DBMS.gdoc',
 'DBMS.pdf',
 'Untitled docume

OSError: [Errno 95] Operation not supported: '../dj'

In [5]:
import cv2 as cv
import os
import numpy as np

os.mkdir(os.path.join(data_path, 'gray_image'))

for i in os.listdir(os.path.join(data_path, 'alphaset')):
    if i in ['Alphabetical Hand gesture recognition using deep learning.ipynb', '.ipynb_checkpoints', 'images.csv']:
        continue

    class_gray_dir = os.path.join(data_path, 'gray_image', i)
    os.mkdir(class_gray_dir)
    for j in os.listdir(os.path.join(data_path, 'alphaset', i)):
        image_path = os.path.join(data_path, 'alphaset', i, j)
        image = cv.imread(image_path)
        if image is None:
            continue

        gray_image = np.mean(image, axis=2).astype(np.uint8)
        print(j)
        print(gray_image)

        save_path = os.path.join(class_gray_dir, f'gray_{j}')
        cv.imwrite(save_path, gray_image)


Streaming output truncated to the last 5000 lines.
Z_451.jpg
[[28 24 26 ... 29 28 31]
 [24 22 24 ... 31 29 30]
 [24 24 27 ... 35 32 33]
 ...
 [21 20 25 ... 17 16 15]
 [22 19 23 ... 16 16 16]
 [26 20 21 ... 18 17 18]]
Z_41.jpg
[[30 25 27 ... 26 29 30]
 [25 23 26 ... 27 28 29]
 [26 26 31 ... 33 32 32]
 ...
 [23 24 25 ... 17 17 15]
 [24 21 23 ... 17 16 16]
 [26 23 23 ... 19 18 20]]
Z_424.jpg
[[29 24 26 ... 24 26 27]
 [24 21 25 ... 26 24 25]
 [24 22 28 ... 30 26 26]
 ...
 [23 22 27 ... 61 53 50]
 [23 20 24 ... 61 53 48]
 [25 20 22 ... 57 56 53]]
Z_370.jpg
[[29 23 25 ... 25 27 28]
 [25 20 24 ... 26 25 25]
 [25 21 28 ... 30 27 26]
 ...
 [22 20 25 ... 65 58 54]
 [23 19 22 ... 65 59 56]
 [26 20 22 ... 66 61 60]]
Z_400.jpg
[[29 24 25 ... 25 27 29]
 [24 20 23 ... 26 25 25]
 [25 23 27 ... 30 26 25]
 ...
 [23 23 26 ... 65 59 54]
 [23 20 22 ... 66 60 54]
 [25 21 22 ... 64 62 62]]
Z_401.jpg
[[28 24 25 ... 24 27 28]
 [24 21 23 ... 25 24 24]
 [25 23 27 ... 29 26 25]
 ...
 [22 22 25 ... 67 63 59]
 [22 

In [12]:
import cv2 as cv
import os
import numpy as np
import pandas as pd

import cv2 as cv
import pandas as pd

data = []
image = cv.imread('A/A_0.jpg')
image = image.flatten()
num_pixels = image.size

columns = ['pixel' + str(k) for k in range(num_pixels)] + ['label']
d = pd.DataFrame([], columns=columns)
for i in os.listdir(data_path):
    if i in ['Alphabetical Hand gesture recognition using deep learning.ipynb', '.ipynb_checkpoints', 'images.csv']:
        continue
    for j in os.listdir(os.path.join(data_path, i)):
        image = cv.imread(os.path.join(data_path, i, j))
        if image is None:
            continue
        image = image.flatten()
        label = ord(i)
        d.loc[len(d)] = np.append(image, label)

d.to_csv('images1.csv', index=False)


AttributeError: 'NoneType' object has no attribute 'flatten'

In [11]:
import pandas as pd
import numpy as np
images=pd.read_csv('images.csv')
print(images.head(10))

                    pixels label
0  [20 81 17 ...  7 33  9]     A
1  [14 74 13 ... 11 37 13]     A
2  [23 81 22 ... 23 46 24]     A
3  [20 82 22 ... 19 43 19]     A
4  [16 76 15 ... 11 38 12]     A
5  [12 72 11 ...  7 33  9]     A
6  [12 72 11 ... 10 36 12]     A
7  [15 75 14 ...  6 32  8]     A
8  [17 78 14 ...  9 36 10]     A
9  [14 74 13 ...  8 35  9]     A


In [ ]:

arr=np.array(images['pixels'][0])
# print(type(arr))
# for i in range(arr.size):
#   print(arr[i])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [ ]:
import re
import ast
all_images_average_pixels = []

for index, row in images.iterrows():
    pixel_str = row['pixels']
    pixel_values_str = re.sub(r'[\[\]...]', '', pixel_str).split()
    pixel_values = [int(val) for val in pixel_values_str]

    average_of_threes = [
        sum(pixel_values[i:i+3]) / 3
        for i in range(0, len(pixel_values), 3)
        if len(pixel_values[i:i+3]) == 3
    ]

    all_images_average_pixels.append(average_of_threes)

images['average_pixels'] = all_images_average_pixels

print("Calculated average of every three consecutive pixel values for all images.")
display(images.tail())

images.to_csv('images_with_avg_pixels.csv', index=False)
print("DataFrame with average pixels saved to 'images_with_avg_pixels.csv'")

images_loaded = pd.read_csv('images_with_avg_pixels.csv')
images_loaded['average_pixels'] = images_loaded['average_pixels'].apply(ast.literal_eval)

print("CSV loaded back with 'average_pixels' as lists.")
display(images_loaded.tail())


Calculated average of every three consecutive pixel values for all images.


pixels label              average_pixels
26058  [ 9 67  9 ... 10 34 10]     Z  [28.333333333333332, 18.0]
26059  [10 68 10 ...  9 33  9]     Z  [29.333333333333332, 17.0]
26060  [10 68  9 ... 11 35 11]     Z                [29.0, 19.0]
26061  [ 4 61  6 ...  8 31  9]     Z  [23.666666666666668, 16.0]
26062  [13 68 11 ... 11 36 10]     Z  [30.666666666666668, 19.0]

DataFrame with average pixels saved to 'images_with_avg_pixels.csv'
CSV loaded back with 'average_pixels' as lists.


pixels label              average_pixels
26058  [ 9 67  9 ... 10 34 10]     Z  [28.333333333333332, 18.0]
26059  [10 68 10 ...  9 33  9]     Z  [29.333333333333332, 17.0]
26060  [10 68  9 ... 11 35 11]     Z                [29.0, 19.0]
26061  [ 4 61  6 ...  8 31  9]     Z  [23.666666666666668, 16.0]
26062  [13 68 11 ... 11 36 10]     Z  [30.666666666666668, 19.0]

In [ ]:
import pandas as pd
l=['a', 'b', 'c', 'd']
d=pd.DataFrame([l, l], columns=('a', 'b', 'c', 'd'))
d.to_csv('dj.csv', index=False)

a  b  c  d
0  a  b  c  d
1  a  b  c  d
2  1  2  3  4