<a href="https://colab.research.google.com/github/SanjayD23/Alphabetical-Hand-gesture-recognition-using-deep-leaning/blob/main/Alphabetical_Hand_gesture_recognition_using_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-learn

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import os
data_path = "/content/drive/MyDrive/"
os.chdir(data_path)
os.listdir(data_path)

['SignAlphaSet (1)',
 'SignAlphaSet',
 'SignAlphaSet.zip',
 'gray_image',
 'images.csv']

In [4]:
os.getcwd()

'/content/drive/MyDrive'

In [ ]:
import cv2 as cv
import os
import numpy as np

os.mkdir(os.path.join(data_path, 'gray_image'))

for i in os.listdir(os.path.join(data_path, 'alphaset')):
    if i in ['Alphabetical Hand gesture recognition using deep learning.ipynb', '.ipynb_checkpoints', 'images.csv']:
        continue

    class_gray_dir = os.path.join(data_path, 'gray_image', i)
    os.mkdir(class_gray_dir)
    for j in os.listdir(os.path.join(data_path, 'alphaset', i)):
        image_path = os.path.join(data_path, 'alphaset', i, j)
        image = cv.imread(image_path)
        if image is None:
            continue

        gray_image = np.mean(image, axis=2).astype(np.uint8)
        print(j)
        print(gray_image)

        save_path = os.path.join(class_gray_dir, f'gray_{j}')
        cv.imwrite(save_path, gray_image)


Streaming output truncated to the last 5000 lines.
Z_451.jpg
[[28 24 26 ... 29 28 31]
 [24 22 24 ... 31 29 30]
 [24 24 27 ... 35 32 33]
 ...
 [21 20 25 ... 17 16 15]
 [22 19 23 ... 16 16 16]
 [26 20 21 ... 18 17 18]]
Z_41.jpg
[[30 25 27 ... 26 29 30]
 [25 23 26 ... 27 28 29]
 [26 26 31 ... 33 32 32]
 ...
 [23 24 25 ... 17 17 15]
 [24 21 23 ... 17 16 16]
 [26 23 23 ... 19 18 20]]
Z_424.jpg
[[29 24 26 ... 24 26 27]
 [24 21 25 ... 26 24 25]
 [24 22 28 ... 30 26 26]
 ...
 [23 22 27 ... 61 53 50]
 [23 20 24 ... 61 53 48]
 [25 20 22 ... 57 56 53]]
Z_370.jpg
[[29 23 25 ... 25 27 28]
 [25 20 24 ... 26 25 25]
 [25 21 28 ... 30 27 26]
 ...
 [22 20 25 ... 65 58 54]
 [23 19 22 ... 65 59 56]
 [26 20 22 ... 66 61 60]]
Z_400.jpg
[[29 24 25 ... 25 27 29]
 [24 20 23 ... 26 25 25]
 [25 23 27 ... 30 26 25]
 ...
 [23 23 26 ... 65 59 54]
 [23 20 22 ... 66 60 54]
 [25 21 22 ... 64 62 62]]
Z_401.jpg
[[28 24 25 ... 24 27 28]
 [24 21 23 ... 25 24 24]
 [25 23 27 ... 29 26 25]
 ...
 [22 22 25 ... 67 63 59]
 [22 

In [ ]:
import cv2 as cv
import os
import numpy as np
import csv

data_path = "/content/drive/MyDrive/gray_image"

sample_class = os.listdir(data_path)[0]
sample_image_path = os.path.join(data_path, sample_class, os.listdir(os.path.join(data_path, sample_class))[0])
sample_image = cv.imread(sample_image_path, cv.IMREAD_GRAYSCALE)
num_pixels = sample_image.size


columns = ['pixel' + str(k) for k in range(num_pixels)] + ['label']


with open('/content/drive/MyDrive/images.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(columns)

    for class_name in os.listdir(data_path):
        class_dir = os.path.join(data_path, class_name)
        for image_name in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_name)
            image = cv.imread(image_path, cv.IMREAD_GRAYSCALE)
            if image is None:
                continue
            flattened = image.flatten()
            label = ord(class_name[0])
            writer.writerow(np.append(flattened, label))


In [16]:
import pandas as pd
import numpy as np
images=pd.read_csv('images.csv', nrows=2000)
print(images.head())

   pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      31      31      32      35      37      37      36      36      36   
1      29      23      25      31      30      28      28      27      28   
2      28      23      24      29      29      27      27      27      28   
3      32      31      32      35      36      34      33      33      35   
4      29      24      25      30      29      28      29      27      28   

   pixel9  ...  pixel87607  pixel87608  pixel87609  pixel87610  pixel87611  \
0      35  ...          35          38          37          38          41   
1      28  ...          16          15          18          16          17   
2      27  ...          13          14          16          14          18   
3      33  ...          41          41          43          43          42   
4      28  ...          14          12          16          15          14   

   pixel87612  pixel87613  pixel87614  pixel87615  label  
0        

In [9]:
images.head(900)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0        31      31      32      35      37      37      36      36      36   
1        29      23      25      31      30      28      28      27      28   
2        28      23      24      29      29      27      27      27      28   
3        32      31      32      35      36      34      33      33      35   
4        29      24      25      30      29      28      29      27      28   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
895      33      28      28      31      31      30      30      31      34   
896      29      23      24      29      31      28      27      27      28   
897      29      24      25      28      29      28      27      27      30   
898      32      29      29      31      33      31      29      29      29   
899      25      21      23      26      27      28      26      26      26   

     pixel9  ...  pixel87607  pixel87608  pixel87609  pixel87610  pixel87611  \
0        35  ...          35          38          37          38          41   
1        28  ...          16          15          18          16          17   
2        27  ...          13          14          16          14          18   
3        33  ...          41          41          43          43          42   
4        28  ...          14          12          16          15          14   
..      ...  ...         ...         ...         ...         ...         ...   
895      33  ...          47          47          45          46          43   
896      28  ...          17          18          16          16          18   
897      30  ...          43          45          45          46          46   
898      29  ...          42          45          44          47          45   
899      27  ...          43          44          44          43          42   

     pixel87612  pixel87613  pixel87614  pixel87615  label  
0            40          36          34          34     67  
1            16          16          14          18     67  
2            16          15          13          19     67  
3            42          41          36          30     67  
4            15          13          13          17     67  
..          ...         ...         ...         ...    ...  
895          47          41          40          40     67  
896          16          14          14          17     67  
897          45          44          42          40     67  
898          47          44          45          43     67  
899          41          40          39          38     67  

[900 rows x 87617 columns]

In [ ]:

arr=np.array(images['pixels'][0])
# print(type(arr))
# for i in range(arr.size):
#   print(arr[i])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [ ]:
import pandas as pd
l=['a', 'b', 'c', 'd']
d=pd.DataFrame([l, l], columns=('a', 'b', 'c', 'd'))
d.to_csv('dj.csv', index=False)

a  b  c  d
0  a  b  c  d
1  a  b  c  d
2  1  2  3  4

In [4]:
os.chdir("/content/drive/MyDrive/")

In [5]:
import pandas as pd
sample = pd.read_csv("images.csv", nrows=10)
print(sample.head())

   pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      31      31      32      35      37      37      36      36      36   
1      29      23      25      31      30      28      28      27      28   
2      28      23      24      29      29      27      27      27      28   
3      32      31      32      35      36      34      33      33      35   
4      29      24      25      30      29      28      29      27      28   

   pixel9  ...  pixel87607  pixel87608  pixel87609  pixel87610  pixel87611  \
0      35  ...          35          38          37          38          41   
1      28  ...          16          15          18          16          17   
2      27  ...          13          14          16          14          18   
3      33  ...          41          41          43          43          42   
4      28  ...          14          12          16          15          14   

   pixel87612  pixel87613  pixel87614  pixel87615  label  
0        

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import IncrementalPCA


csv_path = "images.csv"


chunksize = 2000
n_components = 300
batch_size = chunksize


scaler = StandardScaler()
ipca = IncrementalPCA(n_components=n_components, batch_size=batch_size)


print("Fitting Incremental PCA...")
for chunk in pd.read_csv(csv_path, chunksize=chunksize):

    X_chunk = chunk.iloc[:, :-1].values


    X_scaled = scaler.fit_transform(X_chunk)


    ipca.partial_fit(X_scaled)

print("Fitting complete!")

print("Transforming dataset...")
X_pca_list = []
y_list = []

for chunk in pd.read_csv(csv_path, chunksize=chunksize):
    X_chunk = chunk.iloc[:, :-1].values
    y_chunk = chunk.iloc[:, -1].values


    X_scaled = scaler.transform(X_chunk)


    X_pca_chunk = ipca.transform(X_scaled)

    X_pca_list.append(X_pca_chunk)
    y_list.append(y_chunk)


X_pca = np.vstack(X_pca_list)
y = np.concatenate(y_list)

print("Original shape:", (len(y), 87617))
print("Reduced shape:", X_pca.shape)


reduced_df = pd.DataFrame(X_pca)
reduced_df["label"] = y
reduced_df.to_csv("images_reduced.csv", index=False)

print("Reduced dataset saved as images_reduced.csv")


Fitting Incremental PCA...


In [ ]:
import re

def parse_pixel_string(pixel_str):
    pixel_values_str = re.sub(r'[\[\]...]', '', pixel_str).split()
    return [int(val) for val in pixel_values_str]

images['parsed_pixels'] = images['pixels'].apply(parse_pixel_string)
print("Converted pixel strings to numerical arrays in 'parsed_pixels' column.")
images.head()

Converted pixel strings to numerical arrays in 'parsed_pixels' column.


pixels label          pixels_processed  \
0  [20 81 17 ...  7 33  9]     A    [20, 81, 17, 7, 33, 9]   
1  [14 74 13 ... 11 37 13]     A  [14, 74, 13, 11, 37, 13]   
2  [23 81 22 ... 23 46 24]     A  [23, 81, 22, 23, 46, 24]   
3  [20 82 22 ... 19 43 19]     A  [20, 82, 22, 19, 43, 19]   
4  [16 76 15 ... 11 38 12]     A  [16, 76, 15, 11, 38, 12]   

              parsed_pixels  
0    [20, 81, 17, 7, 33, 9]  
1  [14, 74, 13, 11, 37, 13]  
2  [23, 81, 22, 23, 46, 24]  
3  [20, 82, 22, 19, 43, 19]  
4  [16, 76, 15, 11, 38, 12]

In [ ]:
X = np.array(images['parsed_pixels'].tolist())
y = images['label'].values

print("Shape of features (X):", X.shape)
print("Shape of target (y):", y.shape)
print("Features (X) head:\n", X[:5])
print("Target (y) head:\n", y[:5])

Shape of features (X): (26063, 6)
Shape of target (y): (26063,)
Features (X) head:
 [[20 81 17  7 33  9]
 [14 74 13 11 37 13]
 [23 81 22 23 46 24]
 [20 82 22 19 43 19]
 [16 76 15 11 38 12]]
Target (y) head:
 ['A' 'A' 'A' 'A' 'A']


In [ ]:
pca_features_list = []
unique_labels = np.unique(y)

for label in unique_labels:
    X_class = X[y == label]
    y_class = y[y == label]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_class)

    pca = PCA(n_components=0.95)
    X_pca = pca.fit_transform(X_scaled)

    pc_columns = [f"PC_{i+1}" for i in range(X_pca.shape[1])]
    df_pca_class = pd.DataFrame(data=X_pca, columns=pc_columns)
    df_pca_class['label'] = y_class

    pca_features_list.append(df_pca_class)

print("PCA applied to each class and results stored in 'pca_features_list'.")
print(f"Number of DataFrames in pca_features_list: {len(pca_features_list)}")
print("Example of a PCA-transformed DataFrame (first class):")
display(pca_features_list[0].head())

PCA applied to each class and results stored in 'pca_features_list'.
Number of DataFrames in pca_features_list: 26
Example of a PCA-transformed DataFrame (first class):


PC_1      PC_2 label
0 -2.718577 -1.255547     A
1 -0.635304 -1.807080     A
2 -0.496518  2.179596     A
3 -1.108388  1.254788     A
4 -1.090495 -1.345898     A

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca_overall = PCA(n_components=0.95)
X_pca = pca_overall.fit_transform(X_scaled)

print("Shape of X_scaled:", X_scaled.shape)
print("Shape of X_pca (after overall PCA):", X_pca.shape)
print("Number of components retained by overall PCA:", X_pca.shape[1])


Shape of X_scaled: (26063, 6)
Shape of X_pca (after overall PCA): (26063, 3)
Number of components retained by overall PCA: 3


In [ ]:
pc_overall_columns = [f"PC_{i+1}" for i in range(X_pca.shape[1])]
x_pca_df = pd.DataFrame(data=X_pca, columns=pc_overall_columns)
x_pca_df['label'] = y

x_pca_df.to_csv('pca_features_overall.csv', index=False)
print("Combined PCA-transformed features with labels and saved to 'pca_features_overall.csv'.")
print("Shape of the overall PCA features DataFrame:", x_pca_df.shape)
print("Head of the overall PCA features DataFrame:")
display(x_pca_df.head())

Combined PCA-transformed features with labels and saved to 'pca_features_overall.csv'.
Shape of the overall PCA features DataFrame: (26063, 4)
Head of the overall PCA features DataFrame:


PC_1      PC_2      PC_3 label
0 -0.022616  3.325803  0.502168     A
1 -0.261501  1.360273  0.126387     A
2  1.273932  4.257219  1.006416     A
3  0.919681  4.013250  0.414706     A
4 -0.067899  2.076088  0.281343     A

In [ ]:
print("Variance explained by each principal component:", pca_overall.explained_variance_ratio_)
print(f"PC_1 explains {pca_overall.explained_variance_ratio_[0]:.2%} of the variance.")
print(f"PC_2 explains {pca_overall.explained_variance_ratio_[1]:.2%} of the variance.")
print(f"PC_3 explains {pca_overall.explained_variance_ratio_[2]:.2%} of the variance.")

print(f"The first 3 principal components cumulatively explain {pca_overall.explained_variance_ratio_.sum():.2%} of the variance.")

Variance explained by each principal component: [0.49274314 0.40949896 0.06388748]
PC_1 explains 49.27% of the variance.
PC_2 explains 40.95% of the variance.
PC_3 explains 6.39% of the variance.
The first 3 principal components cumulatively explain 96.61% of the variance.


In [ ]:
import pandas as pd
pca_df = pd.read_csv('/content/drive/MyDrive/pca_features_overall.csv')
print(f"The dimensions of the PCA-transformed data are: {pca_df.shape}")
print(f"The DataFrame has {pca_df.shape[0]} rows (samples) and {pca_df.shape[1]} columns (features + label).")

The dimensions of the PCA-transformed data are: (26063, 4)
The DataFrame has 26063 rows (samples) and 4 columns (features + label).


In [ ]:
print('Original feature names (pixel values):')
original_features = [f'pixel{i}' for i in range(X.shape[1])]
print(original_features)

print('\nPrincipal Components (Eigenvectors):')
# The rows of `pca_overall.components_` are the principal components
# and the columns correspond to the original features.
display(pd.DataFrame(pca_overall.components_, columns=original_features, index=['PC_1', 'PC_2', 'PC_3']))

Original feature names (pixel values):
['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5']

Principal Components (Eigenvectors):


pixel0    pixel1    pixel2    pixel3    pixel4    pixel5
PC_1  0.153888  0.145132  0.145403  0.554795  0.563974  0.555202
PC_2  0.539387  0.542531  0.590771 -0.144119 -0.146297 -0.153422
PC_3  0.707501 -0.705437 -0.001255  0.030480 -0.018671 -0.022860

### Interpreting the Principal Components:

*   **Rows represent Principal Components:** Each row in the table above corresponds to a principal component (`PC_1`, `PC_2`, `PC_3`).
*   **Columns represent Original Features:** Each column corresponds to one of your original pixel features (`pixel0`, `pixel1`, `pixel2`, etc.).
*   **Values are Loadings:** The values in the table are called 'loadings'. These loadings indicate the **correlation** between the original pixel features and the principal components. A higher absolute value (either positive or negative) for a loading means that the original pixel feature contributes more significantly to that particular principal component.

For example:

*   If `pixel0` has a large loading for `PC_1`, it means that `pixel0` is a strong contributor to `PC_1` and changes in `pixel0` significantly influence `PC_1`'s score.
*   The sign of the loading (positive or negative) indicates the direction of the relationship. A positive loading means that as the pixel value increases, the PC score tends to increase (or vice-versa). A negative loading means that as the pixel value increases, the PC score tends to decrease (or vice-versa).

By examining these loadings, you can get a sense of which combinations of your original pixel values define the new principal component dimensions.